name: Publish nested package

on:
  workflow_dispatch:

env:
  NODE_VERSION: 14.x

jobs:
  prepare:
    name: prepare
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2.4.1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

  semantic-release:
    name: semantic release
    needs: prepare
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/package1
    outputs:
      isReleasePublished: ${{ steps.set-new-release.outputs.isReleasePublished }}
      releaseVersion: ${{ steps.set-new-release.outputs.releaseVersion }}
      releaseNotes: ${{ steps.set-new-release.outputs.releaseNotes }}
    steps:
      - name: Run Semantic Release
        working-directory: ./packages/package1
        id: semantic
        uses: cycjimmy/semantic-release-action@v2
        with:
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Get release ${{ env.RELEASE_VERSION }} details (isReleasePublished -> ${{ env.IS_RELEASE_PUBLISHED }})
        id: set-new-release
        run: |
          echo "::set-output name=isReleasePublished::$IS_RELEASE_PUBLISHED"
          echo "::set-output name=releaseVersion::$RELEASE_VERSION"
          echo "::set-output name=releaseNotes::$RELEASE_NOTES"
        env:
          IS_RELEASE_PUBLISHED: ${{ steps.semantic.outputs.new_release_published }}
          RELEASE_VERSION: ${{ steps.semantic.outputs.new_release_version }}
          RELEASE_NOTES: ${{ steps.semantic.outputs.new_release_notes }}
